### ISSUE TITLE
Basic drivetrain

### ISSUE THREAD

**Issue by camilo86** [FTC-NUTRONS/SBA2015#1]
Using two joysticks and two motors 

1. Get Left & Right joystick values
2. Write Joystick values to their corresponding motors
3. Test functionality

**Comment by mustafa320** [comment]
ok

**Comment by mrweeee** [comment]
O M G

ok camilo 
ven pronto

**Comment by mrweeee** [comment]
oky doki

**Comment by mustafa320** [comment]
Done due to a599d23edd119d3238fdb15c4a97e9c57be0fbfe
